import type { GuideContext, KnowledgeTypeState } from '../api/guideContext';

/**
 * Explore prompt generation (Step 16).
 *
 * ARCHITECTURE DECISION: prompts are built ON THE DEVICE from context the
 * backend already provides (`/guides/{id}/context` and
 * `/guides/{id}/knowledge-state`), rather than generated by an LLM and
 * persisted server-side.
 *
 * Why, having considered both:
 *   - No new persistence, no prompt lifecycle, no idempotency questions, no
 *     "what happens to a stale prompt row" problem.
 *   - No LLM latency or cost on a tab the guide may open dozens of times a
 *     day, and no network round-trip beyond the two context reads.
 *   - Prompts are suggestions, not commitments. Nothing downstream references
 *     a prompt id, so there is nothing to keep referentially intact. (Contrast
 *     Questions, which ARE persisted, assigned, and answered — that difference
 *     is exactly why the two systems are separate.)
 *   - It keeps the LLM budget where it earns the most: extraction, where it
 *     turns free text into structured knowledge.
 *
 * The honesty rule that governs every line of copy below: a prompt may only
 * name a place if the backend actually resolved one. When it didn't, the copy
 * falls back to place-neutral wording. Explore never tells a guide they are
 * "near Pangong Lake" on a guess.
 */

export type ExplorePromptKind =
  | 'conditions'
  | 'photo'
  | 'story'
  | 'discovery'
  | 'culture'
  | 'local_find';

export interface ExplorePrompt {
  /** Stable within a rendering, used as a React key and stored as local-only
   * provenance on the contribution (see LocalCapture.explorePromptId). */
  id: string;
  kind: ExplorePromptKind;
  /** Short card heading. */
  title: string;
  /** The actual invitation shown to the guide. */
  body: string;
  /** Placeholder for the compose field — sets the expected shape of an answer. */
  placeholder: string;
  /**
   * Invitation shown on the voice-note control (Step 17), phrased for THIS
   * prompt so recording feels like answering the question rather than
   * operating a generic widget.
   *
   * Governed by the same honesty rule as every other line here: it may only
   * name a place when the backend actually resolved one, and it never implies
   * the app knows something it doesn't. It is derived from the prompt the guide
   * is already looking at — never independently invented.
   */
  voiceCopy: string;
  /** True when this prompt is specifically asking for a picture. Drives the
   * compose screen opening with the photo actions foregrounded. */
  wantsPhoto: boolean;
  /** Present only when the prompt was built from a REAL knowledge gap the
   * backend reported. Rendered as a small explanatory line so the guide can
   * see why they're being asked — never invented. */
  reason: string | null;
}

/** Copy templates. `place` is pre-resolved to either a real place name or a
 * neutral phrase before these are used — see buildPrompts. */
interface Template {
  kind: ExplorePromptKind;
  title: string;
  body: (place: string, hasRealPlace: boolean) => string;
  placeholder: string;
  voiceCopy: (place: string, hasRealPlace: boolean) => string;
  wantsPhoto: boolean;
}

const TEMPLATES: Template[] = [
  {
    kind: 'photo',
    title: 'Photo moment',
    body: (place, real) =>
      real
        ? `How does ${place} actually look right now? A photo tells the next guide more than a forecast can.`
        : 'How does it look where you are right now? A photo tells the next guide more than a forecast can.',
    placeholder: 'Say what the photo shows…',
    voiceCopy: (place, real) =>
      real ? `Describe ${place} out loud` : 'Tell us what it looks like right now',
    wantsPhoto: true,
  },
  {
    kind: 'conditions',
    title: 'What you can see',
    body: (place, real) =>
      real
        ? `You're near ${place}. What stands out about the conditions here at the moment?`
        : "What stands out about the conditions where you're standing right now?",
    placeholder: 'Weather, ground, water, anything you notice…',
    voiceCopy: () => 'Say what the conditions are like',
    wantsPhoto: false,
  },
  {
    kind: 'story',
    title: 'Local knowledge',
    body: (place, real) =>
      real
        ? `Do people here tell a story about ${place} that a visitor would never find in a guidebook?`
        : 'Is there a story about this place that a visitor would never find in a guidebook?',
    placeholder: 'What locals say about this place…',
    voiceCopy: () => 'Share the story in your own words',
    wantsPhoto: false,
  },
  {
    kind: 'discovery',
    title: 'Worth passing on',
    body: () =>
      'Noticed something today another traveller would genuinely want to know before they set out?',
    placeholder: "Anything you'd want to be told yourself…",
    voiceCopy: () => 'Tell us what you noticed',
    wantsPhoto: false,
  },
  {
    kind: 'culture',
    title: 'Easy to miss',
    body: (place, real) =>
      real
        ? `What do most visitors walk straight past at ${place} without realising it matters?`
        : 'What do most visitors walk straight past here without realising it matters?',
    placeholder: 'The thing people overlook…',
    voiceCopy: () => 'Say what people walk past',
    wantsPhoto: false,
  },
  {
    kind: 'local_find',
    title: 'A good find',
    body: () =>
      'Found somewhere worth stopping — food, shelter, water, a view, a person worth knowing?',
    placeholder: 'What you found and why it is worth it…',
    voiceCopy: () => 'Tell us what you found',
    wantsPhoto: false,
  },
];

/**
 * Deterministic rotation seed. Derived from the day and the guide's rounded
 * coordinates, so the deck feels alive as the guide moves or as days pass, but
 * is STABLE within a place and a day — reopening the tab doesn't reshuffle
 * everything under the guide's fingers, and pull-to-refresh isn't a slot
 * machine. Coordinates are rounded to ~1km so tiny GPS jitter doesn't
 * reshuffle the deck while standing still.
 */
function rotationSeed(context: GuideContext | null): number {
  const day = Math.floor(Date.now() / 86_400_000);
  if (!context) return day;
  const lat = Math.round(context.latitude * 100);
  const lon = Math.round(context.longitude * 100);
  // Small mixing constants; this only needs to spread values, not be a hash.
  return day * 31 + lat * 7 + lon * 13;
}

/** Human phrasing for how out-of-date a knowledge type is. Only ever called
 * with a real backend state — never invents a duration. */
function describeGap(state: KnowledgeTypeState): string | null {
  switch (state.state) {
    case 'missing':
      return `Nobody has reported ${state.displayName.toLowerCase()} around here yet`;
    case 'stale':
      return `The last ${state.displayName.toLowerCase()} report here is out of date`;
    case 'aging':
      return `The ${state.displayName.toLowerCase()} report here is getting old`;
    default:
      return null;
  }
}

/**
 * Builds the Explore deck.
 *
 * `knowledgeStates` contributes GROUNDED prompts: for each real gap the
 * backend reports at this location, one prompt is emitted that names the
 * actual knowledge type and explains why it's being asked. Those come first,
 * because they're the ones where an answer measurably improves what the system
 * knows. Open-ended discovery prompts follow — Explore is explicitly not just
 * a gap queue, and a guide should always be able to tell us something we never
 * thought to ask.
 *
 * Returns an empty array only when there is genuinely nothing to offer, which
 * the UI renders as its own honest state rather than a fake card.
 */
export function buildPrompts(
  context: GuideContext | null,
  knowledgeStates: KnowledgeTypeState[] | null
): ExplorePrompt[] {
  const place = context?.nearestKnownPlace?.name ?? null;
  const hasRealPlace = place !== null;
  const placeLabel = place ?? 'here';

  const prompts: ExplorePrompt[] = [];

  // 1. Grounded prompts, from REAL gaps the backend reported. Safety-critical
  //    gaps first, then missing before stale before aging — the same urgency
  //    order the backend's own ranking uses (knowledge_decisions.py), applied
  //    here purely for display ordering.
  const urgency: Record<string, number> = { missing: 0, stale: 1, aging: 2 };
  const gaps = (knowledgeStates ?? [])
    .filter((s) => s.state !== 'fresh')
    .sort((a, b) => {
      if (a.safetyCritical !== b.safetyCritical) return a.safetyCritical ? -1 : 1;
      return (urgency[a.state] ?? 9) - (urgency[b.state] ?? 9);
    })
    // Two at most: Explore is a discovery surface, not a backlog. The full
    // operational queue lives in the Questions tab.
    .slice(0, 2);

  for (const gap of gaps) {
    prompts.push({
      id: `gap:${gap.knowledgeType}`,
      kind: 'conditions',
      title: gap.displayName,
      body: hasRealPlace
        ? `You're near ${placeLabel} — what's the ${gap.displayName.toLowerCase()} like right now?`
        : `What's the ${gap.displayName.toLowerCase()} like where you are right now?`,
      placeholder: `Describe the ${gap.displayName.toLowerCase()} you can see…`,
      voiceCopy: `Tell us about the ${gap.displayName.toLowerCase()} here`,
      wantsPhoto: false,
      reason: describeGap(gap),
    });
  }

  // 2. Open discovery prompts, rotated deterministically.
  const seed = rotationSeed(context);
  const offset = ((seed % TEMPLATES.length) + TEMPLATES.length) % TEMPLATES.length;
  const rotated = [...TEMPLATES.slice(offset), ...TEMPLATES.slice(0, offset)];

  for (const template of rotated) {
    // Skip a generic 'conditions' card when grounded gap cards already asked
    // about conditions — otherwise the deck repeats itself.
    if (template.kind === 'conditions' && gaps.length > 0) continue;
    prompts.push({
      id: `open:${template.kind}`,
      kind: template.kind,
      title: template.title,
      body: template.body(placeLabel, hasRealPlace),
      placeholder: template.placeholder,
      voiceCopy: template.voiceCopy(placeLabel, hasRealPlace),
      wantsPhoto: template.wantsPhoto,
      reason: null,
    });
  }

  return prompts;
}

/** The always-available "tell us anything" path. Kept separate from the deck
 * so the UI can present it as a distinct, permanent affordance rather than one
 * more rotating card — a guide must never have to wait for the right prompt to
 * appear in order to report something. */
export const FREE_FORM_PROMPT: ExplorePrompt = {
  id: 'open:free_form',
  kind: 'discovery',
  title: 'Share anything',
  body: "Seen something we didn't think to ask about? Tell us in your own words.",
  placeholder: 'Anything worth recording…',
  voiceCopy: 'Say it in your own words',
  wantsPhoto: false,
  reason: null,
};
