"""add index for knowledge state observation lookups

Revision ID: 50ec37a29ef0
Revises: 19af3d0d9eb9
Create Date: 2026-08-26 17:37:19.535546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50ec37a29ef0'
down_revision: Union[str, None] = '19af3d0d9eb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_observations_knowledge_type_id_observed_at', 'observations', ['knowledge_type_id', 'observed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_observations_knowledge_type_id_observed_at', table_name='observations')
    # ### end Alembic commands ###
