"""add questions and question_assignments tables

Revision ID: d85a0d520a5c
Revises: 50ec37a29ef0
Create Date: 2026-08-26 18:18:06.394081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd85a0d520a5c'
down_revision: Union[str, None] = '50ec37a29ef0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_request_id', sa.String(length=255), nullable=True),
    sa.Column('knowledge_type_id', sa.UUID(), nullable=False),
    sa.Column('gap_state', sa.String(length=20), nullable=False),
    sa.Column('target_latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('target_longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('nearest_known_place_name', sa.String(length=255), nullable=True),
    sa.Column('nearest_known_place_distance_meters', sa.Float(), nullable=True),
    sa.Column('safety_critical', sa.Boolean(), nullable=False),
    sa.Column('default_priority', sa.Integer(), nullable=False),
    sa.Column('staleness_severity_hours', sa.Float(), nullable=False),
    sa.Column('gap_rank', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=True),
    sa.Column('short_context', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_type_id'], ['knowledge_type_config.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_request_id')
    )
    op.create_index('ix_questions_status', 'questions', ['status'], unique=False)
    op.create_table('question_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('guide_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guide_id'], ['guides.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_question_assignments_guide_id_status', 'question_assignments', ['guide_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_question_assignments_guide_id_status', table_name='question_assignments')
    op.drop_table('question_assignments')
    op.drop_index('ix_questions_status', table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
