"""add question answers and submission provenance

Revision ID: e166034d56a0
Revises: d85a0d520a5c
Create Date: 2026-08-26 18:40:35.776563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e166034d56a0'
down_revision: Union[str, None] = 'd85a0d520a5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('guide_id', sa.UUID(), nullable=False),
    sa.Column('client_answer_id', sa.String(length=255), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['question_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guide_id'], ['guides.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_answer_id')
    )
    op.create_index('ix_question_answers_question_id', 'question_answers', ['question_id'], unique=False)
    op.add_column('submissions', sa.Column('source_question_id', sa.UUID(), nullable=True))
    op.create_index('ix_submissions_source_question_id', 'submissions', ['source_question_id'], unique=False)
    op.create_foreign_key(None, 'submissions', 'questions', ['source_question_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.drop_index('ix_submissions_source_question_id', table_name='submissions')
    op.drop_column('submissions', 'source_question_id')
    op.drop_index('ix_question_answers_question_id', table_name='question_answers')
    op.drop_table('question_answers')
    # ### end Alembic commands ###
